// Generated by IcedCoffeeScript 1.6.2c
(function() {


  document.addEventListener('DOMContentLoaded', function() {
    var chart_id, chart_size, el, height, images, match, src, to_convert, tuple, width, _i, _j, _len, _len1, _results;
    images = document.getElementsByTagName("img");
    console.log(images);
    to_convert = [];
    for (_i = 0, _len = images.length; _i < _len; _i++) {
      el = images[_i];
      console.log(el);
      src = el.getAttribute("src");
      console.log(src);
      match = src.match(/compare.open-budget.org.il\/images\/([a-z]+)\/([a-z-0-9]+)\.jpg/);
      console.log(match);
      if (match) {
        chart_size = match[1];
        chart_id = match[2];
        to_convert.push([el, chart_size, chart_id]);
      }
    }
    _results = [];
    for (_j = 0, _len1 = to_convert.length; _j < _len1; _j++) {
      tuple = to_convert[_j];
      el = tuple[0];
      chart_size = tuple[1];
      chart_id = tuple[2];
      console.log(chart_id, chart_size, el);
      width = null;
      height = null;
      if (chart_size === "small") {
        width = 460;
        height = 808;
      }
      if (chart_size === "medium") {
        width = 637;
        height = 734;
      }
      if (chart_size === "large") {
        width = 959;
        height = 719;
      }
      if (width && height) {
        _results.push(el.outerHTML = "<iframe src='//compare.open-budget.org.il/vis.html?" + chart_id + "' width='" + width + "' height='" + height + "'>" + el.outerHTML + "</iframe>");
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

}).call(this);
