// Generated by IcedCoffeeScript 1.6.2c
(function() {
  var BubbleChart, CompareData, L, addState, charts, explanations, first_time, formatNumber, getExplanation, globalSelectedItem, globalTooltipItem, globalTooltipShown, gotExplanations, gotStories, handleNewState, iced, init, removeState, showTooltip, state, stories, __iced_k, __iced_k_noop, _ref, _ref1,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = {
    Deferrals: (function() {
      function _Class(_arg) {
        this.continuation = _arg;
        this.count = 1;
        this.ret = null;
      }

      _Class.prototype._fulfill = function() {
        if (!--this.count) {
          return this.continuation(this.ret);
        }
      };

      _Class.prototype.defer = function(defer_params) {
        var _this = this;
        ++this.count;
        return function() {
          var inner_params, _ref;
          inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          if (defer_params != null) {
            if ((_ref = defer_params.assign_fn) != null) {
              _ref.apply(null, inner_params);
            }
          }
          return _this._fulfill();
        };
      };

      return _Class;

    })(),
    findDeferral: function() {
      return null;
    },
    trampoline: function(_fn) {
      return _fn();
    }
  };
  __iced_k = __iced_k_noop = function() {};

  L = function() {
    var x;
    x = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return console.log.apply(console, x);
  };

  formatNumber = function(n, decimals) {
    var negativePrefix, negativeSuffix, num, prefix, remainder, s, suffix;
    suffix = "";
    negativePrefix = "";
    negativeSuffix = "";
    if (n < 0) {
      negativePrefix = " הכנסה של";
      negativeSuffix = "";
      n = -n;
    }
    if (n >= 1000000000000) {
      suffix = " trillion";
      n = n / 1000000000000;
      decimals = 2;
    } else if (n >= 1000000000) {
      suffix = " מיליארד";
      n = n / 1000000000;
      decimals = 1;
    } else if (n >= 1000000) {
      suffix = " מיליון";
      n = n / 1000000;
      decimals = 1;
    }
    prefix = "";
    if (decimals > 0) {
      if (n < 1) {
        prefix = "0";
      }
      s = String(Math.round(n * (Math.pow(10, decimals))));
      if (s < 10) {
        remainder = "0" + s.substr(s.length - decimals, decimals);
        num = "";
      } else {
        remainder = s.substr(s.length - decimals, decimals);
        num = s.substr(0, s.length - decimals);
      }
      return negativePrefix + prefix + num.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,") + "." + remainder + suffix + negativeSuffix;
    } else {
      s = String(Math.round(n));
      s = s.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
      return negativePrefix + s + suffix + negativeSuffix;
    }
  };

  CompareData = (function(_super) {
    __extends(CompareData, _super);

    function CompareData() {
      _ref = CompareData.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    CompareData.prototype.defaults = {
      data: [],
      field: "",
      title: "?",
      link: null
    };

    CompareData.prototype.initialize = function() {
      return this.on('change:field', function() {
        var data, field;
        field = this.get('field');
        data = budget_array_data[field];
        if (data) {
          this.set('code', data.c);
          this.set('link', data.l);
          this.set('title', data.t);
          return this.set('data', data.d);
        }
      });
    };

    return CompareData;

  })(Backbone.Model);

  globalSelectedItem = null;

  globalTooltipItem = null;

  globalTooltipShown = false;

  showTooltip = function(d, xpos, ypos, that) {
    var bcodes, history_text, itemNumber, pctchngout, svgPos, tail;
    if (!globalTooltipItem) {
      d3.select("#tooltip").style('display', 'none');
      globalTooltipShown = false;
      return;
    }
    svgPos = $("div.chart:last").offset();
    tail = 107.5;
    xpos += that.centerX;
    if (xpos < 135) {
      tail += 135 - xpos;
      xpos = 135;
    }
    if (xpos > (that.width - 135)) {
      tail -= xpos - (that.width - 135);
      xpos = that.width - 135;
    }
    xpos += 4;
    if (ypos > -that.height / 4) {
      ypos = ypos - d.radius - 10 + svgPos.top + that.centerY;
      $("#tooltipContainer").css("bottom", 0);
      d3.select("#tooltip .arrow.top").style("display", "none");
      d3.select("#tooltip .arrow.bottom").style("display", "block");
    } else {
      ypos = ypos + d.radius + 10 + svgPos.top + that.centerY;
      $("#tooltipContainer").css("bottom", "");
      d3.select("#tooltip .arrow.top").style("display", "block");
      d3.select("#tooltip .arrow.bottom").style("display", "none");
    }
    d3.select("#tooltip").style('top', ypos + "px").style('left', xpos + "px");
    if (globalTooltipShown) {
      return;
    }
    d3.select("#tooltip").style('display', 'block').classed('plus', d.changeCategory > 0).classed('minus', d.changeCategory < 0).classed('newitem', d.newitem).classed('disappeared', d.disappeared);
    d3.select("#tooltip .name").html(d.name);
    itemNumber = d.code;
    if (d.bcodes.length > 0) {
      bcodes = _.map(d.bcodes, (function(x) {
        return x[0];
      }));
      if ((bcodes.length !== 1) || (bcodes[0] !== d.code)) {
        itemNumber += " (" + (bcodes.join(",")) + " ב-2012)";
      }
    }
    d3.select("#tooltip .itemNumber").text(itemNumber);
    d3.select("#tooltip .explanation").html(getExplanation(d.sid, 2014, d.name));
    if (d.history) {
      history_text = "XXX";
      if (d.history > 0) {
        if (that.income) {
          history_text = "מ2009 ההכנסות עברו ב" + d.history + "%+ בממוצע את התחזית";
        } else {
          history_text = "מ2009 ההוצאות חורגות ב" + d.history + "%+ בממוצע מהתכנון";
        }
      } else if (d.history < 0) {
        if (that.income) {
          history_text = "מ-2009 בממוצע ההכנסות פספסו ב " + (-d.history) + "% את התחזית";
        } else {
          history_text = "מ-2009 בממוצע " + (-d.history) + "% מהתקציב אינו מנוצל";
        }
      }
      if (d.history !== 0) {
        d3.select("#tooltip .history").text(history_text).classed("plus", d.history > 0).classed("minus", d.history < 0).attr("data-categories", "" + d.changeCategory + ":" + d.projectedChangeCategory);
      }
    } else {
      d3.select("#tooltip .history").text("");
    }
    d3.select("#tooltip .value").html(formatNumber(d.value * 1000) + " \u20aa");
    d3.selectAll("#tooltip .arrow").style("right", tail + "px");
    if (d != null ? d.changestr : void 0) {
      pctchngout = d.changestr;
    } else {
      pctchngout = d.change === "N.A." ? "N.A" : that.pctFormat(Math.abs(d.change));
    }
    pctchngout = pctchngout + (d.change < 0 ? "-" : "+");
    d3.select("#tooltip .change").html(pctchngout);
    return globalTooltipShown = true;
  };

  BubbleChart = (function(_super) {
    __extends(BubbleChart, _super);

    function BubbleChart() {
      _ref1 = BubbleChart.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    BubbleChart.prototype.fillColor = function(changeCategory) {
      var _fillColor;
      _fillColor = d3.scale.ordinal().domain([-4, -3, -2, -1, 0, 1, 2, 3, 4]).range(["#9F7E01", "#dbae00", "#eac865", "#f5dd9c", "#AAA", "#bfc3dc", "#9ea5c8", "#7b82c2", "#464FA1"]);
      return _fillColor(changeCategory);
    };

    BubbleChart.prototype.strokeColor = function(code, changeCategory) {
      var _strokeColor;
      if (code === globalSelectedItem) {
        return "#FF0";
      }
      _strokeColor = d3.scale.ordinal().domain([-4, -3, -2, -1, 0, 1, 2, 3, 4]).range(["#796001", "#c09100", "#e7bd53", "#d9c292", "#999", "#a7aed3", "#7f8ab8", "#4f5fb0", "#1A2055"]);
      return _strokeColor(changeCategory);
    };

    BubbleChart.prototype.getFillColor = function(d) {
      return this.fillColor(d.changeCategory);
    };

    BubbleChart.prototype.getStrokeColor = function(d) {
      return this.strokeColor(d.sid, d.changeCategory);
    };

    BubbleChart.prototype.getProjFillColor = function(d) {
      return this.fillColor(d.projectedChangeCategory);
    };

    BubbleChart.prototype.getProjStrokeColor = function(d) {
      return this.strokeColor(null, d.projectedChangeCategory);
    };

    BubbleChart.prototype.strokeWidth = function(d) {
      if (d.code === globalSelectedItem) {
        return 5;
      } else {
        return 1;
      }
    };

    BubbleChart.prototype.pctFormat = function(p) {
      var pFormat;
      pFormat = d3.format(".1%");
      if (p === Infinity || p === -Infinity) {
        return "N.A";
      } else {
        return pFormat(p);
      }
    };

    BubbleChart.prototype.defaultCharge = function(d) {
      if (d.value < 0) {
        return 0;
      } else {
        return -Math.pow(d.radius, 2.0) / 8;
      }
    };

    BubbleChart.prototype.totalSort = function(alpha) {
      var _this = this;
      return function(d) {
        var bump, cat, radiusx, radiusy, targetX, targetY;
        cat = _this.budget_categories[d.sid];
        targetX = targetY = 0;
        bump = 0.02;
        radiusx = 10;
        radiusy = 0;
        if (_this.showSplit) {
          radiusx = _this.width * 0.2;
          radiusy = _this.height * 0.15;
          bump = 0.04;
        }
        if (cat && cat !== 7) {
          cat = cat * Math.PI * 0.333;
          targetY = radiusy * Math.sin(cat);
          targetX = radiusx * Math.cos(cat);
        }
        if (d.isNegative) {
          if (d.changeCategory > 0) {
            d.x = -200;
          } else {
            d.x = 1100;
          }
        }
        d.y = d.y + (targetY - d.y) * (_this.defaultGravity + bump) * alpha;
        return d.x = d.x + (targetX - d.x) * (_this.defaultGravity + bump) * alpha;
      };
    };

    BubbleChart.prototype.buoyancy = function(alpha) {
      var _this = this;
      return function(d) {
        var targetY;
        targetY = -(d.changeCategory / 3) * _this.boundingRadius;
        return d.y = d.y + (targetY - d.y) * _this.defaultGravity * alpha * alpha * alpha * 500;
      };
    };

    BubbleChart.prototype.categorizeChange = function(c) {
      if (isNaN(c)) {
        return 0;
      }
      if (c < -0.5) {
        return -4;
      }
      if (c < -0.25) {
        return -3;
      }
      if (c < -0.05) {
        return -2;
      }
      if (c < -0.001) {
        return -1;
      }
      if (c <= 0.001) {
        return 0;
      }
      if (c <= 0.05) {
        return 1;
      }
      if (c <= 0.25) {
        return 2;
      }
      if (c <= 0.5) {
        return 3;
      }
      return 4;
    };

    BubbleChart.prototype.setOverlayed = function(overlayed) {
      overlayed = overlayed ? true : false;
      if (overlayed) {
        return this.transitiontime = 0;
      } else {
        return this.transitiontime = 1000;
      }
    };

    BubbleChart.prototype.initialize = function(options) {
      var search, that, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      this.options = options;
      _.bindAll(this);
      this.width = 970;
      this.height = 550;
      this.id = this.options.id;
      this.overlayShown = false;
      this.showSplit = false;
      this.categories = null;
      this.defaultGravity = 0.1;
      this.force = this.svg = this.circle = null;
      this.centerX = this.width / 2;
      this.centerY = this.height / 2;
      this.model.bind('change:data', function() {
        return _this.updateData(_this.model.get('data'));
      });
      d3.select(this.el).html("");
      this.svg = d3.select(this.el).append("svg:svg");
      this.svg.on("click", function() {
        removeState();
        return false;
      });
      $("div[data-id='" + this.id + "'] .btnSpend").click(function() {
        state.querys = ["00"];
        History.pushState(state, null, "?" + state.querys.join("/"));
        return false;
      });
      $("div[data-id='" + this.id + "'] .btnIncome").click(function() {
        state.querys = ["0000"];
        History.pushState(state, null, "?" + state.querys.join("/"));
        return false;
      });
      $("div[data-id='" + this.id + "'] .splitter").click(function() {
        _this.showSplit = !_this.showSplit;
        _this.svg.selectAll("g.splitter circle").transition().duration(500).style("opacity", _this.showSplit ? 1 : 0);
        _this.svg.selectAll("g.splitter text").transition().duration(500).style("opacity", _this.showSplit ? 1 : 0);
        $("div[data-id='" + _this.id + "'] .splitter").toggleClass("on", _this.showSplit);
        _this.force.start();
        console.log("LL", _this.showSplit);
        return false;
      });
      this.budget_categories = {
        "0001": 2,
        "0002": 2,
        "0003": 2,
        "0004": 2,
        "0005": 2,
        "0006": 2,
        "0007": 1,
        "0008": 2,
        "0009": 2,
        "0010": 1,
        "0011": 2,
        "0012": 6,
        "0013": 2,
        "0014": 2,
        "0015": 1,
        "0016": 1,
        "0017": 1,
        "0018": 2,
        "0019": 4,
        "0020": 3,
        "0021": 3,
        "0023": 3,
        "0024": 3,
        "0025": 3,
        "0026": 4,
        "0027": 3,
        "0029": 5,
        "0030": 3,
        "0032": 4,
        "0033": 4,
        "0034": 5,
        "0035": 4,
        "0036": 4,
        "0037": 4,
        "0038": 4,
        "0039": 4,
        "0040": 5,
        "0041": 5,
        "0042": 5,
        "0043": 5,
        "0045": 6,
        "0046": 1,
        "0051": 3,
        "0052": 1,
        "0053": 2,
        "0054": 4,
        "0056": 3,
        "0060": 3,
        "0067": 3,
        "0068": 2,
        "0070": 5,
        "0073": 5,
        "0076": 4,
        "0078": 4,
        "0079": 5,
        "0083": 5,
        "0084": 6,
        "0055": 1,
        "0047": 7
      };
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "vis.coffee",
          funcname: "BubbleChart.initialize"
        });
        setTimeout((__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return __iced_deferrals.ret = arguments[0];
            };
          })(),
          lineno: 272
        })), 100);
        __iced_deferrals._fulfill();
      })(function() {
        that = _this;
        search = $("div[data-id='" + _this.id + "'] .mysearch");
        $("div[data-id='" + _this.id + "'] .mysearch-open").click(function() {
          search.select2("open");
          return false;
        });
        search.select2({
          placeholder: "חפשו סעיף ספציפי",
          allowClear: true,
          data: function() {
            console.log("Titles: ", _this.titles);
            return {
              'results': _this.titles
            };
          }
        });
        return search.on("select2-open", function(e) {
          return $("div[data-id='" + that.id + "'] .breadcrumbs").css("visibility", "hidden");
        }).on("select2-close", function(e) {
          return $("div[data-id='" + that.id + "'] .breadcrumbs").css("visibility", "visible");
        }).on("select2-highlight", function(e) {
          return that.selectItem({
            code: e.choice.id
          });
        }).on("change", function(e) {
          var x, _i, _len, _ref2;
          if (e.added) {
            that.selectItem({
              code: e.added.id
            });
            _ref2 = e.added.state;
            for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
              x = _ref2[_i];
              addState(x);
            }
            return search.select2("val", "");
          } else {
            return that.selectItem(null);
          }
        });
      });
    };

    BubbleChart.prototype.collectTitles = function(titles, field, prefix, _state) {
      var code, data, n, name, _i, _len, _ref2, _results;
      if (prefix == null) {
        prefix = '';
      }
      if (_state == null) {
        _state = [];
      }
      if (!field) {
        return;
      }
      data = budget_array_data[field];
      if (data) {
        _ref2 = data.d;
        _results = [];
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          n = _ref2[_i];
          code = n.id;
          name = n.n;
          if (name && code) {
            titles.push({
              id: code,
              text: prefix + name,
              code: code,
              state: _state,
              fullpath: data.c + ";" + code
            });
          }
          _results.push(this.collectTitles(titles, n.d, prefix + name + ' | ', _state.concat([n.d])));
        }
        return _results;
      }
    };

    BubbleChart.prototype.updateData = function(data) {
      var container, currentYearDataColumn, n, node, oldNodes, out, previousYearDataColumn, rScale, radiusScale, sid, sum, x, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref2;
      oldNodes = [];
      sum = 0;
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        x = data[_i];
        sum += x.b1;
      }
      this.totalValue = sum != null ? sum : 400000000;
      if (typeof this !== "undefined" && this !== null ? this.nodes : void 0) {
        _ref2 = this.nodes;
        for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
          node = _ref2[_j];
          oldNodes.push(node);
        }
      }
      this.nodes = [];
      this.titles = [];
      this.collectTitles(this.titles, this.model.get('field'));
      rScale = d3.scale.pow().exponent(0.5).domain([0, this.totalValue]).range([7, 165]);
      radiusScale = function(n) {
        return rScale(Math.abs(n));
      };
      this.boundingRadius = radiusScale(this.totalValue);
      currentYearDataColumn = 'b1';
      previousYearDataColumn = 'b0';
      for (_k = 0, _len2 = data.length; _k < _len2; _k++) {
        n = data[_k];
        out = null;
        sid = n.id;
        for (_l = 0, _len3 = oldNodes.length; _l < _len3; _l++) {
          node = oldNodes[_l];
          if (node.sid === sid) {
            out = node;
          }
        }
        if (out === null) {
          out = {
            x: -150 + Math.random() * 300,
            y: -150 + Math.random() * 300
          };
        }
        out.sid = n.id;
        out.code = n.jc;
        out.radius = radiusScale(n[currentYearDataColumn]);
        out.change = n.c / 100.0;
        out.changeCategory = this.categorizeChange(n.c / 100.0);
        out.value = n[currentYearDataColumn];
        out.name = n.n;
        out.isNegative = n[currentYearDataColumn] < 0;
        out.positions = n.positions;
        out.drilldown = n.d;
        out.history = n.pp;
        out.bcodes = n.bc;
        if (out.history) {
          out.projectedValue = out.value * (out.history + 100) / 100.0;
          out.projectedRadius = radiusScale(out.projectedValue);
          out.projectedChangeCategory = this.categorizeChange(((n.c + 100) * (n.pp + 100) - 10000) / 10000.0);
        }
        /*
        #  if (n.positions.total) 
                	    	#     out.x = n.positions.total.x + (n.positions.total.x - (@width / 2)) * 0.5
                	    	#     out.y = n.positions.total.y + (n.positions.total.y - (150)) * 0.5
        */

        if ((n[currentYearDataColumn] > 0) && (n[previousYearDataColumn] < 0)) {
          out.changestr = "הפך מהכנסה להוצאה";
          out.changeCategory = 4;
        }
        if ((n[currentYearDataColumn] < 0) && (n[previousYearDataColumn] > 0)) {
          out.changestr = "הפך מהוצאה להכנסה";
          out.changeCategory = -4;
        }
        out.newitem = false;
        out.disappeared = false;
        if (n.c === 99999) {
          out.changestr = "תוקצב מחדש";
          out.changeCategory = 4;
          out.newitem = true;
        }
        if (out.value === 0) {
          out.disappeared = true;
          out.value = n[previousYearDataColumn];
          out.radius = radiusScale(n[previousYearDataColumn]);
        }
        this.nodes.push(out);
      }
      this.nodes.sort(function(a, b) {
        return Math.abs(b.value) - Math.abs(a.value);
      });
      this.titles.sort(function(a, b) {
        if (a.code > b.code) {
          return 1;
        } else {
          return -1;
        }
      });
      if (data.length > 0) {
        return this.render();
      } else {
        container = $("div[data-id='" + this.id + "']");
        if (this.transitiontime > 0) {
          this.circle.transition().duration(this.transitiontime).attr("r", function(d) {
            return 0;
          });
          return container.find(".overlay").css("opacity", 0.9).animate({
            opacity: 0
          }, this.transitiontime, function() {
            return container.remove();
          });
        } else {
          return container.remove();
        }
      }
    };

    BubbleChart.prototype.showOverlay = function(id) {
      var node, origin, scale, target, _i, _len, _node, _ref2;
      if (this.overlayShown) {
        return;
      }
      this.overlayShown = true;
      node = null;
      _ref2 = this.nodes;
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        _node = _ref2[_i];
        if (_node.drilldown === id) {
          node = _node;
        }
      }
      if (node === null) {
        return;
      }
      scale = this.height / node.radius / 3;
      origin = "translate(" + this.centerX + "," + this.centerY + ")rotate(0)translate(1,1)scale(1)";
      target = "translate(" + this.centerX + "," + this.centerY + ")rotate(120)translate(" + (-node.x * scale) + "," + (-node.y * scale) + ")scale(" + scale + ")";
      if (this.transitiontime === 0) {
        this.svg.selectAll("circle,text").attr("transform", target);
      } else {
        this.svg.selectAll("circle,text").transition().duration(this.transitiontime).attrTween("transform", function() {
          return d3.interpolateString(origin, target);
        });
      }
      return $("#tooltip").hide();
    };

    BubbleChart.prototype.overlayRemoved = function() {
      var origin, target;
      this.setOverlayed(false);
      this.overlayShown = false;
      origin = this.svg.select("circle").attr("transform");
      target = "translate(" + this.centerX + "," + this.centerY + ")rotate(0)translate(1,1)scale(1)";
      this.svg.selectAll("circle,text").transition().duration(this.transitiontime).attrTween("transform", function() {
        return d3.interpolateString(origin, target);
      });
      return this.circle.attr("r", function(d) {
        return d.radius;
      });
    };

    BubbleChart.prototype.selectItem = function(d) {
      globalSelectedItem = d.code;
      this.circle.style("stroke-width", this.strokeWidth);
      return this.circle.style("stroke", this.getStrokeColor);
    };

    BubbleChart.prototype.open_modal = function(select) {
      var field, first, item_select, set_path, that, titles, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      that = this;
      $(".modal").remove();
      $(".modal-template").clone().appendTo('body');
      $(".modal-template:last").toggleClass("modal-template", false).toggleClass("modal", true);
      $(".modal .tab-pane").each(function(e) {
        return $(this).attr("id", $(this).attr("data-id"));
      });
      $(".modal nav-pills a").tab();
      $(".modal li").toggleClass("active", false);
      $(".modal a[href='" + select + "']").parent().toggleClass("active", true);
      $(".modal .tab-pane").toggleClass("active", false);
      $(".modal " + select).toggleClass("active", true);
      $('.modal .modal-footer .btn-primary').css("display", "none");
      $('.modal .modal-footer [data-rel="' + select + '"]').css("display", "inherit");
      $('.modal a[data-toggle="tab"]').on('shown', function(e) {
        var _select;
        _select = $(e.target).attr("href");
        $('.modal .modal-footer .btn-primary').css("display", "none");
        return $('.modal .modal-footer [data-rel="' + _select + '"]').css("display", "inherit");
      });
      field = that.model.get('field');
      $(".modal .shareItemDetails h3").text(this.model.get('title'));
      $(".modal .shareItemDetails p").html(getExplanation(field));
      titles = _.map(that.nodes, function(d) {
        return {
          id: d.sid,
          text: d.name,
          title: d.name,
          path: field + ";" + d.sid
        };
      });
      titles.unshift({
        id: field,
        text: "בחירת התרשים כמות שהוא",
        title: that.model.get('title'),
        path: field
      });
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "vis.coffee",
          funcname: "BubbleChart.open_modal"
        });
        setTimeout((__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return __iced_deferrals.ret = arguments[0];
            };
          })(),
          lineno: 483
        })), 100);
        __iced_deferrals._fulfill();
      })(function() {
        item_select = $(".modal .item-select");
        set_path = function(path, title, code) {
          $(".modal .embed-code").val("<iframe src='http://compare.open-budget.org.il/?" + path + "' width='640' height='900'/>");
          $(".modal .direct-link").val("http://compare.open-budget.org.il/?" + path);
          $(".modal .facebook-share").click(function() {
            var sharer;
            sharer = "https://www.facebook.com/sharer/sharer.php?u=http://compare.open-budget.org.il/of/" + path + ".html";
            window.open(sharer, 'sharer', 'width=626,height=436');
            window.ga('send', 'event', 'share', 'facebook');
            return false;
          });
          $(".modal .shareItemDetails h3").text(title);
          $(".modal .shareItemDetails p").html(getExplanation(code));
          $(".modal .shareThumb").attr("src", "http://compare.open-budget.org.il/images/large/" + path + ".jpg");
          $(".modal .shareThumb").attr("alt", title);
          return $(".modal .photo-download").click(function() {
            var sharer;
            sharer = "http://compare.open-budget.org.il/images/large/" + path + ".jpg";
            window.open(sharer, 'sharer');
            window.ga('send', 'event', 'share', 'photo');
            return false;
          });
        };
        item_select.select2({
          placeholder: "שיתוף התרשים הנוכחי",
          allowClear: false,
          data: titles
        }).on("change", function(e) {
          var code, path, title;
          if (e.added) {
            path = e.added.path;
            title = e.added.title;
            code = e.added.id;
            console.log("AAA", path);
            item_select.select2("close");
            return set_path(path, title, code);
          }
        });
        set_path(field);
        first = true;
        $(".modal").modal();
        $(".modal").modal("show");
        return $(".modal").on("shown", function() {
          var ___iced_passed_deferral1, __iced_deferrals, __iced_k,
            _this = this;
          __iced_k = __iced_k_noop;
          ___iced_passed_deferral1 = iced.findDeferral(arguments);
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral1,
              filename: "vis.coffee"
            });
            setTimeout((__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return __iced_deferrals.ret = arguments[0];
                };
              })(),
              lineno: 522
            })), 100);
            __iced_deferrals._fulfill();
          })(function() {
            if (first) {
              item_select.select2("open");
              return first = false;
            }
          });
        }).on("hide", function() {
          return item_select.select2("close");
        });
      });
    };

    BubbleChart.prototype.render = function() {
      var chartContainer, container, frame, moreinfo, overlay, resizeFrame, tagClicked, tags, that,
        _this = this;
      that = this;
      this.field = this.model.get('field');
      this.income = this.field.indexOf("0000") === 0;
      this.root = this.field === "00" || this.field === "0000";
      $("div[data-id='" + this.id + "'] .btnSpend").css("display", "none");
      $("div[data-id='" + this.id + "'] .btnIncome").css("display", "none");
      $("div[data-id='" + this.id + "'] .splitter").css("display", "none");
      if (this.income) {
        moreinfo = "הכנסות בפועל 2012 לעומת תחזית הכנסות 2014, שיעור השינוי הוא ריאלי";
      } else {
        moreinfo = "תקציב מקורי 2012 לעומת תקציב מקורי 2014, שיעור השינוי הוא ריאלי";
      }
      $("div[data-id='" + this.id + "'] .moreinfo").text(moreinfo);
      if (this.income && this.root) {
        $("div[data-id='" + this.id + "'] .btnSpend").css("display", "inherit");
      }
      if ((!this.income) && this.root) {
        $("div[data-id='" + this.id + "'] .btnIncome").css("display", "inherit");
        $("div[data-id='" + this.id + "'] .splitter").css("display", "inherit");
      }
      this.setBreadcrumbs = function(dd) {
        var actual_querys, bc, depth, link, mshLinkCode, query, title, _i, _j, _len, _len1, _ref2;
        if (dd == null) {
          dd = null;
        }
        bc = $("div[data-id='" + _this.id + "'] .breadcrumbs");
        bc.find(".breadpart").remove();
        actual_querys = [];
        _ref2 = state.querys;
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          query = _ref2[_i];
          actual_querys.push(query);
          if (query === _this.model.get('field')) {
            break;
          }
        }
        depth = actual_querys.length;
        for (_j = 0, _len1 = actual_querys.length; _j < _len1; _j++) {
          query = actual_querys[_j];
          depth -= 1;
          title = budget_array_data[query].t;
          if (depth > 0) {
            bc.append("<span class='breadpart breadcrumbsParent' data-up='" + depth + "'>" + title + "</span>");
            bc.append("<span class='breadpart breadcrumbsSeparator'></span>");
          } else {
            bc.append("<span class='breadpart breadcrumbsCurrent'>" + title + "</span>");
          }
        }
        bc.find(".breadcrumbsParent").click(function() {
          var up_count;
          up_count = parseInt($(this).attr('data-up'));
          removeState(up_count);
          return false;
        });
        mshLinkCode = null;
        if (!dd) {
          mshLinkCode = _this.model.get('code');
        } else {
          bc.append("<span class='breadpart breadcrumbsSeparator'></span>");
          bc.append("<span class='breadpart breadcrumbsChild'>" + dd.name + "</span>");
          mshLinkCode = dd.sid;
        }
        if (mshLinkCode) {
          bc.append('<span class="breadpart breadcrumbsMsh"><a class="breadcrumbsLink" target="_new" href="http://budget.msh.gov.il/#' + mshLinkCode + ',2014,0,1,1,1,0,0,0,0,0,0" class="active" data-toggle="tooltip" data-placement="bottom" title="מידע היסטורי אודות הסעיף הנוכחי">' + '<i class="icon-bar-chart icon"></i></a></span><!--i class="icon-book icon-flip-horizontal icon"></i-->');
        }
        link = _this.model.get('link');
        if (link) {
          bc.append('<span class="breadpart breadcrumbsGov"><a class="breadcrumbsLink" target="_new" href="' + link + '" ' + 'class="active" data-toggle="tooltip" data-placement="bottom" title="עיון בספר התקציב במשרד האוצר">' + '<i class="icon-book icon-flip-horizontal icon"></i></a></span>');
        }
        $("div[data-id='" + _this.id + "'] .breadcrumbsLink").click(function() {
          window.ga('send', 'event', 'learn', $(this).attr("href"));
          return true;
        });
        return $("div[data-id='" + _this.id + "'] .breadcrumbsLink").tooltip();
      };
      this.setBreadcrumbs();
      $("div[data-id='" + this.id + "'] .splitter").tooltip();
      $("div[data-id='" + this.id + "'] .btnIncome").tooltip();
      $("div[data-id='" + this.id + "'] .btnSpend").tooltip();
      $("div[data-id='" + this.id + "'] .btnBack").tooltip();
      $("div[data-id='" + this.id + "'] .share-button").tooltip();
      $("div[data-id='" + this.id + "'] .share-button").click(function() {
        return that.open_modal($(this).attr('data-tab-href'));
      });
      $("div[data-id='" + this.id + "'] .color-index").tooltip();
      if (false) {
        tags = $("div[data-id='" + this.id + "'] .tag");
        tagClicked = false;
        tags.mouseenter(function() {
          that.selectItem($(this).text());
          return tagClicked = false;
        }).mouseleave(function() {
          if (!tagClicked) {
            return that.selectItem(null);
          }
        }).click((function() {
          that.selectItem($(this).text());
          tagClicked = true;
          return false;
        }));
      }
      container = $("div[data-id='" + this.id + "'] .overlayContainer");
      chartContainer = $("div[data-id='" + this.id + "'] .chartContainer");
      overlay = $("div[data-id='" + this.id + "'] .overlay");
      frame = $("div[data-id='" + this.id + "'] .frame");
      resizeFrame = function() {
        _this.width = $(window).width() - 8;
        if (_this.width > 900) {
          _this.width = 900;
        }
        _this.centerX = _this.width / 2 + 4;
        _this.svg.attr("width", _this.width);
        _this.svg.style("width", _this.width + "px");
        if (!_this.overlayShown && _this.circle) {
          _this.svg.selectAll("circle").attr("transform", "translate(" + _this.centerX + "," + _this.centerY + ")rotate(0)translate(0,0)scale(1)");
        }
        overlay.css("height", (chartContainer.height()) + "px");
        if (chartContainer.offset()) {
          return overlay.css("top", (chartContainer.offset().top) + "px");
        }
      };
      $(window).resize(resizeFrame);
      resizeFrame();
      if (this.transitiontime > 0) {
        overlay.css("opacity", 0).animate({
          opacity: 0.9
        }, this.transitiontime);
      } else {
        overlay.css("opacity", 0.9);
      }
      this.circle = this.svg.selectAll("circle.regular").data(this.nodes, function(d) {
        return d.sid;
      });
      that = this;
      this.circle.enter().append("svg:circle").attr("transform", "translate(" + this.centerX + "," + this.centerY + ")rotate(0)translate(0,0)scale(1)").attr("data-title", function(d) {
        return d.name;
      }).style("stroke-width", this.strokeWidth).style("fill", this.getFillColor).style("stroke", this.getStrokeColor).style("cursor", function(d) {
        if (budget_array_data[d.drilldown]) {
          return "pointer";
        } else {
          return "default";
        }
      }).classed('regular', true).classed('newitem', function(d) {
        return d.newitem;
      }).classed('disappeared', function(d) {
        return d.disappeared;
      }).on("click", function(d, i) {
        if (budget_array_data[d.drilldown]) {
          addState(d.drilldown);
        }
        d3.event.stopPropagation();
        return false;
      }).on("mouseover", function(d, i) {
        var anim, el;
        el = d3.select(this);
        if (false && !d.newitem && !d.disappeared) {
          anim = that.svg.insert("svg:circle", ":first-child").attr("cx", el.attr("cx")).attr("cy", el.attr("cy")).attr("transform", el.attr("transform")).attr("r", el.attr("r")).style("stroke", el.style("stroke")).style("fill", el.style("fill")).classed("tooltiphelper-" + d.sid, true);
          anim.transition().duration(500).attr("r", d.projectedRadius).style("fill", that.getProjFillColor(d));
          el.style("stroke-dasharray", "5,5").style("fill", "rgba(255,255,255,0)");
        }
        if (d.drilldown) {
          el.style("stroke", "#000").style("stroke-width", 3);
        }
        globalTooltipItem = d.sid;
        return showTooltip(d, Number(el.attr('cx')), Number(el.attr('cy')), that);
      }).on("mouseout", function(d, i) {
        globalTooltipItem = null;
        d3.selectAll("circle.tooltiphelper-" + d.sid).remove();
        d3.select(this).attr("r", d.radius).style("stroke-width", that.strokeWidth).style("stroke", that.getStrokeColor(d)).style("stroke-dasharray", null).style("fill", that.getFillColor(d));
        return showTooltip();
      });
      if (this.transitiontime > 0) {
        this.circle.transition().duration(this.transitiontime).attr("r", function(d) {
          return d.radius;
        }).style("fill", function(d) {
          return _this.getFillColor(d);
        }).style("stroke", function(d) {
          return _this.getStrokeColor(d);
        });
        this.circle.exit().transition().duration(this.transitiontime).attr("r", function(d) {
          return 0;
        }).remove();
      } else {
        this.circle.attr("r", function(d) {
          return d.radius;
        }).style("fill", function(d) {
          return _this.getFillColor(d);
        }).style("stroke", function(d) {
          return _this.getStrokeColor(d);
        });
        this.circle.exit().remove();
      }
      if (this.force !== null) {
        this.force.stop();
      }
      this.force = d3.layout.force().nodes(this.nodes).size([this.width, this.height]).gravity(-0.01).charge(this.defaultCharge).friction(0.9).on("tick", function(e) {
        var avgx, avgy, i, maxcatx, maxcaty, maxx, maxy, mincatx, mincaty, minx, miny, num, radius, _i, _j, _results;
        maxx = -1000;
        minx = 1000;
        maxy = -1000;
        miny = 1000;
        avgx = 0;
        avgy = 0;
        maxcatx = {};
        mincatx = {};
        maxcaty = {};
        mincaty = {};
        for (i = _i = 1; _i <= 7; i = ++_i) {
          maxcatx[i] = maxcaty[i] = -1000;
          mincatx[i] = mincaty[i] = 1000;
        }
        num = _this.nodes.length;
        _this.circle.each(_this.totalSort(e.alpha)).each(_this.buoyancy(e.alpha)).each(function(d) {
          var cat, _maxx, _maxy, _minx, _miny;
          _maxx = d.x + d.radius;
          _minx = d.x - d.radius;
          _maxy = d.y + d.radius;
          _miny = d.y - d.radius;
          maxx = _maxx > maxx ? _maxx : maxx;
          minx = _minx < minx ? _minx : minx;
          maxy = _maxy > maxy ? _maxy : maxy;
          miny = _miny < miny ? _miny : miny;
          avgx = (maxx + minx) / 2.0;
          avgy = that.centerY + miny - 10;
          cat = that.budget_categories[d.sid];
          if (that.showSplit && cat) {
            maxcatx[cat] = _maxx > maxcatx[cat] ? _maxx : maxcatx[cat];
            mincatx[cat] = _minx < mincatx[cat] ? _minx : mincatx[cat];
            maxcaty[cat] = _maxy > maxcaty[cat] ? _maxy : maxcaty[cat];
            return mincaty[cat] = _miny < mincaty[cat] ? _miny : mincaty[cat];
          }
        }).attr("cx", function(d) {
          return d.x - avgx;
        }).attr("cy", function(d) {
          return d.y - avgy;
        }).each(function(d) {
          if (d.sid === globalTooltipItem) {
            return showTooltip(d, d.x - avgx, d.y, that);
          }
        });
        if (that.showSplit) {
          _results = [];
          for (i = _j = 1; _j <= 7; i = ++_j) {
            radius = (maxcaty[i] - mincaty[i]) > (maxcatx[i] - mincatx[i]) ? maxcaty[i] - mincaty[i] : maxcatx[i] - mincatx[i];
            radius = radius / 2 + 5;
            _this.svg.select("circle[data-category='" + i + "']").attr("cx", (maxcatx[i] + mincatx[i]) / 2 - avgx).attr("cy", (maxcaty[i] + mincaty[i]) / 2 - avgy).attr("r", radius);
            _results.push(_this.svg.selectAll("text[data-category='" + i + "']").attr("x", (maxcatx[i] + mincatx[i]) / 2 - avgx).attr("y", (maxcaty[i] + mincaty[i]) / 2 - avgy + radius));
          }
          return _results;
        }
      }).start();
      return this.initCategories();
    };

    BubbleChart.prototype.initCategories = function() {
      var i, _i, _results;
      if (this.categories != null) {
        return;
      }
      this.categories = [[1, ['הביטחון', 'והסדר הציבורי']], [2, ['המשרדים', 'המנהליים']], [3, ['השירותים', 'החברתיים']], [4, ['ענפי המשק']], [5, ['תשתיות', 'ובינוי']], [6, ['הוצאות', 'מרכזיות', 'אחרות']], [7, ['רזרבות']]];
      this.split_cats = this.svg.append("svg:g");
      this.split_groups = this.split_cats.selectAll("g").data(this.categories).enter().append("svg:g").classed("splitter", true);
      this.split_groups.append("circle").attr("transform", "translate(" + this.centerX + "," + this.centerY + ")rotate(0)translate(0,0)scale(1)").attr("r", 1).attr("cx", 0).attr("cy", 0).style("fill", "none").style("stroke", "#999").style("stroke-width", 1).style("stroke-dasharray", "5,5").style("opacity", 0).attr("data-category", function(d) {
        return d[0];
      });
      _results = [];
      for (i = _i = 0; _i <= 2; i = ++_i) {
        _results.push(this.split_groups.append("text").attr("transform", "translate(" + this.centerX + "," + this.centerY + ")rotate(0)translate(0,0)scale(1)").text(function(d) {
          return d[1][i];
        }).attr("dy", (1.0 * (i + 1)) + "em").attr("width", "100px").attr("height", "20px").style("font-size", "1.2em").style("stroke", "#000").attr("y", 0).attr("x", 0).style("opacity", 0).attr("text-anchor", "middle").attr("data-category", function(d) {
          return d[0];
        }));
      }
      return _results;
    };

    return BubbleChart;

  })(Backbone.View);

  state = {
    querys: [],
    selectedStory: null
  };

  charts = [];

  first_time = true;

  addState = function(toAdd) {
    if (!(state != null ? state.querys : void 0)) {
      state.querys = [];
    }
    state.querys.push(toAdd);
    return History.pushState(state, null, "?" + state.querys.join("/"));
  };

  removeState = function(amount) {
    var i, _i;
    if (amount == null) {
      amount = 1;
    }
    globalTooltipItem = null;
    showTooltip();
    if (state.querys.length > amount) {
      for (i = _i = 0; 0 <= amount ? _i < amount : _i > amount; i = 0 <= amount ? ++_i : --_i) {
        state.querys.pop();
      }
      return History.pushState(state, null, "?" + state.querys.join("/"));
    }
  };

  handleNewState = function() {
    var default_subtitle, el, explanation, i, id, max, nextquery, overlaid, query, subtitle, template, title, _i, _j, _ref2, _ref3, _ref4;
    state = History.getState();
    state = state.data;
    query = "00";
    if (!state.querys || state.querys.length === 0) {
      state.querys = ["00"];
    }
    console.log("New state: ", state.querys);
    if (!state.selectedStory) {
      state.selectedStory = {
        'title': "כך נראה תקציב המדינה בשנתיים הקרובות",
        'subtitle': null
      };
    }
    for (i = _i = 0, _ref2 = state.querys.length; 0 <= _ref2 ? _i < _ref2 : _i > _ref2; i = 0 <= _ref2 ? ++_i : --_i) {
      query = state.querys[i];
      nextquery = state.querys[i + 1];
      id = "id" + i;
      el = $("div[data-id='" + id + "'] .chart");
      if (el.size() === 0) {
        title = ((_ref3 = state.selectedStory) != null ? _ref3.title : void 0) || "התקציב הדו שנתי 2013-2014 לעומת תקציב 2012";
        default_subtitle = 'כך הממשלה מתכוונת להוציא מעל 400 מיליארד שקלים. העבירו את העכבר מעל לעיגולים וגלו כמה כסף מקדישה הממשלה לכל מטרה. לחצו על עיגול בשביל לצלול לעומק התקציב ולחשוף את הפינות החבויות שלו';
        explanation = getExplanation(query);
        if (explanation !== null) {
          default_subtitle = explanation;
        }
        subtitle = state.selectedStory.subtitle || default_subtitle;
        template = _.template($("#chart-template").html(), {
          id: id,
          title: title,
          subtitle: subtitle,
          code: query
        });
        $("#charts").append(template);
        el = $("div[data-id='" + id + "'] .chart");
        charts[i] = new BubbleChart({
          el: el,
          model: new CompareData,
          id: id
        });
      }
    }
    max = state.querys.length > charts.length ? state.querys.length : charts.length;
    for (i = _j = _ref4 = max - 1; _ref4 <= 0 ? _j <= 0 : _j >= 0; i = _ref4 <= 0 ? ++_j : --_j) {
      if (i >= state.querys.length) {
        charts[i].updateData([]);
        charts.pop();
        continue;
      }
      query = state.querys[i];
      overlaid = false;
      if ((i < state.querys.length - 2) || (first_time && (i < state.querys.length - 1))) {
        overlaid = true;
      }
      charts[i].setOverlayed(overlaid);
      charts[i].model.set("field", query);
      if (i < state.querys.length - 1) {
        charts[i].showOverlay(state.querys[i + 1]);
      }
    }
    if (max > state.querys.length) {
      if (charts.length > 0) {
        charts[charts.length - 1].overlayRemoved();
      }
    }
    first_time = false;
    $(".btnBack:first").css("display", "none");
    return window.ga('send', 'pageview', state.querys.join("/"));
  };

  explanations = {};

  getExplanation = function(code, year, title) {
    var explanation, years;
    years = explanations[code];
    explanation = null;
    if (years) {
      year = parseInt(year);
      explanation = years[year];
      if (!explanation) {
        explanation = years[Object.keys(years)[0]];
      }
    }
    if (code !== "0047" && title && title.indexOf("רזרבה") >= 0) {
      if (!explanation) {
        explanation = "";
      }
      explanation += "<b>- תקציב זה מהווה רזרבה לפעילות המשרד/היחידה. אם בסוף השנה היקף הרזרבה יורד ב-100%, זה סימן שהמשרד/היחידה ניצלו את הרזרבה עד תום</b>";
    }
    return explanation;
  };

  gotStories = false;

  gotExplanations = false;

  window.handleExplanations = function(data) {
    var code, entry, explanation, handle_explanation, newrow, row, title, years, _i, _len, _ref2;
    row = 1;
    code = null;
    explanation = null;
    years = null;
    row = null;
    handle_explanation = function(code, explanation, years) {
      var curCodeExpl, year, _i, _len, _results, _year;
      years = years.split(",");
      _results = [];
      for (_i = 0, _len = years.length; _i < _len; _i++) {
        _year = years[_i];
        year = parseInt(_year);
        curCodeExpl = explanations[code];
        if (!curCodeExpl) {
          explanations[code] = {};
          _results.push(explanations[code][year] = explanation);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
    _ref2 = data.feed.entry;
    for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
      entry = _ref2[_i];
      title = entry.title.$t;
      newrow = title.substring(1);
      if (newrow !== row && code !== null && explanation !== null) {
        handle_explanation(code, explanation, years || "");
        code = explanation = years = null;
      }
      if (title.search(/B[0-9]+/) === 0) {
        code = entry.content.$t;
        code = code.indexOf("00") === 0 ? code : "00" + code;
        code = code.indexOf("00X") === 0 || code.indexOf("00x") === 0 ? "00" + code.substring(3) : code;
      }
      if (title.search(/D[0-9]+/) === 0) {
        explanation = entry.content.$t;
      }
      if (title.search(/F[0-9]+/) === 0) {
        years = entry.content.$t;
      }
    }
    gotExplanations = true;
    if (gotStories && gotExplanations) {
      return init();
    }
  };

  stories = {};

  window.handleStories = function(data) {
    var chartid, code, entry, range, row, subtitle, title, _i, _len, _ref2;
    row = 1;
    code = null;
    title = null;
    subtitle = null;
    chartid = null;
    _ref2 = data.feed.entry;
    for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
      entry = _ref2[_i];
      range = entry.title.$t;
      if (range.search(/B[0-9]+/) === 0) {
        code = entry.content.$t;
      }
      if (range.search(/C[0-9]+/) === 0) {
        title = entry.content.$t;
      }
      if (range.search(/D[0-9]+/) === 0) {
        subtitle = entry.content.$t;
      }
      if (range.search(/G[0-9]+/) === 0) {
        chartid = entry.content.$t;
        stories[chartid] = {
          code: code,
          title: title,
          subtitle: subtitle
        };
        code = title = subtitle = chartid = null;
      }
    }
    gotStories = true;
    if (gotStories && gotExplanations) {
      return init();
    }
  };

  init = function() {
    var firstquery, parse, query, ret_query, up, _ref2, _state;
    History.Adapter.bind(window, 'statechange', handleNewState);
    query = "00";
    ret_query = window.location.search.slice(1);
    if (ret_query.length === 0) {
      ret_query = window.location.hash;
      if (ret_query.length > 0) {
        ret_query = query.split("?");
        if (ret_query.length > 1) {
          query = ret_query[1];
        }
      }
    } else {
      query = ret_query;
    }
    if (stories[query]) {
      state.selectedStory = stories[query];
      query = state.selectedStory.code;
    } else {
      state.selectedStory = null;
    }
    parse = query.split(";");
    if (parse.length > 1) {
      query = parse[0];
      globalTooltipItem = globalSelectedItem = parse[1];
    }
    state.querys = query.split("/");
    if (state.querys.length === 1) {
      while (budget_array_data[state.querys[0]]) {
        up = budget_array_data[state.querys[0]].u;
        if (up) {
          state.querys.unshift(up);
        } else {
          break;
        }
      }
    }
    firstquery = state.querys[0];
    if (!state.selectedStory) {
      state.selectedStory = {
        'title': "התקציב הדו שנתי 2013-2014 לעומת תקציב 2012",
        'subtitle': null
      };
    }
    _state = History.getState();
    if (((_ref2 = _state.data) != null ? _ref2.querys : void 0) && _state.data.querys.length > 0) {
      handleNewState();
    } else {
      History.pushState(state, null, "?" + state.querys.join("/"));
    }
    $(document).keyup(function(e) {
      if (e.keyCode === 27) {
        removeState();
      }
      return false;
    });
    return $(".btnBack:last").live("click", function() {
      removeState();
      return false;
    });
  };

  $(function() {
    if ((document.createElementNS != null) && (document.createElementNS('http://www.w3.org/2000/svg', "svg").createSVGRect != null)) {
      handleStories(stories_raw);
      return handleExplanations(explanations_raw);
    }
  });

}).call(this);
